const modalBackdrop=document.getElementById('modalBackdrop');const modalTitle=document.getElementById('modalTitle');const modalSubtitle=document.getElementById('modalSubtitle');const blockBadge=document.getElementById('blockBadge');const floorGrid=document.getElementById('floorGrid');const blockOverview=document.getElementById('blockOverview');const floorView=document.getElementById('floorView');const floorTitle=document.getElementById('floorTitle');const floorChip=document.getElementById('floorChip');const backToFloors=document.getElementById('backToFloors');const closeButton=document.getElementById('modalClose');const campusMap=document.getElementById('campusMap');
let selectedBlock='';let lastFocused=null;let zoomLevel=1;const floorOptions=[{id:'G',label:'Ground',code:'G'},{id:'1',label:'Floor 1',code:'F1'},{id:'2',label:'Floor 2',code:'F2'},{id:'3',label:'Floor 3',code:'F3'},{id:'4',label:'Floor 4',code:'F4'},{id:'5',label:'Floor 5',code:'F5'}];
function blockInitials(name){const map={'Finance Department':'FN','Administrative Block':'AD','A Block':'A','B Block':'B','Bansuri Bhawan':'BB','C Block':'C','Library':'LB','D Block':'D','SC Block':'SC','F Block':'F','E Block':'E'};return map[name]||name.slice(0,2).toUpperCase()}
function renderFloorButtons(){floorGrid.innerHTML=floorOptions.map(f=>`<button class="floor-button" type="button" data-floor="${f.id}"><span class="floor-number">${f.id==='G'?'G':f.id}</span><span class="floor-name">${f.label}</span></button>`).join('');floorGrid.querySelectorAll('.floor-button').forEach(b=>b.addEventListener('click',()=>openFloor(b.dataset.floor)))}
function showModal(blockName,focusTarget){lastFocused=focusTarget||document.activeElement;selectedBlock=blockName;modalTitle.textContent=blockName;modalSubtitle.textContent='Choose a lift or select a floor to continue.';blockBadge.textContent=blockInitials(blockName);blockOverview.classList.remove('hidden');floorView.classList.add('hidden');modalBackdrop.classList.add('open');modalBackdrop.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';closeButton.focus()}
function closeModal(){modalBackdrop.classList.remove('open');modalBackdrop.setAttribute('aria-hidden','true');document.body.style.overflow='';if(lastFocused&&typeof lastFocused.focus==='function')lastFocused.focus()}
function openFloor(id){const floor=floorOptions.find(f=>f.id===id);if(!floor)return;const label=floor.id==='G'?'Ground Floor':`Floor ${floor.id}`;floorTitle.textContent=label;floorChip.textContent=floor.code;modalSubtitle.textContent=`${selectedBlock} · ${label}`;blockOverview.classList.add('hidden');floorView.classList.remove('hidden');backToFloors.focus()}
function backToOverview(){modalSubtitle.textContent='Choose a lift or select a floor to continue.';floorView.classList.add('hidden');blockOverview.classList.remove('hidden')}
document.querySelectorAll('.map-block').forEach(block=>{const handler=()=>showModal(block.dataset.block,block);block.addEventListener('click',handler);block.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();handler()}})});
document.querySelectorAll('.link-placeholder').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();// add link hear
}));
closeButton.addEventListener('click',closeModal);backToFloors.addEventListener('click',backToOverview);modalBackdrop.addEventListener('click',e=>{if(e.target===modalBackdrop)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalBackdrop.classList.contains('open'))closeModal()});
function applyZoom(){campusMap.style.transform=`scale(${zoomLevel})`}document.getElementById('zoomIn').addEventListener('click',()=>{zoomLevel=Math.min(1.25,+(zoomLevel+.1).toFixed(2));applyZoom()});document.getElementById('zoomOut').addEventListener('click',()=>{zoomLevel=Math.max(.9,+(zoomLevel-.1).toFixed(2));applyZoom()});document.getElementById('resetView').addEventListener('click',()=>{zoomLevel=1;applyZoom()});renderFloorButtons();
